spring:
  config:
    activate:
      on-profile: prod

logging:
  file:
    path: ${LOG_PATH:logs}
  level:
    root: INFO
    com.hxuanyu.frogmoker: INFO
    com.hxuanyu.frogmoker.mapper: DEBUG
    org.apache.ibatis: WARN
    com.baomidou.mybatisplus: INFO
